var employees = [{"id":1,"Name":"Brade Abramsky","gender":"Male"},
    {"id":2,"Name":"Colleen Heis","gender":"Female"},
    {"id":3,"Name":"Zebulen Skipper","gender":"Male"},
    {"id":4,"Name":"Blinni Heugle","gender":"Female"},
    {"id":5,"Name":"Wainwright Ocheltree","gender":"Male"},
    {"id":6,"Name":"Carlie McGurgan","gender":"Female"},
    {"id":7,"Name":"Dehlia Braidon","gender":"Non-binary"},
    {"id":8,"Name":"Bettine Justis","gender":"Female"},
    {"id":9,"Name":"Ritchie Styan","gender":"Male"},
    {"id":10,"Name":"Hans Titherington","gender":"Polygender"},
    {"id":11,"Name":"Germaine Sturzaker","gender":"Male"},
    {"id":12,"Name":"Edy Lille","gender":"Female"},
    {"id":13,"Name":"Arte McGarvey","gender":"Male"},
    {"id":14,"Name":"Frederick Bundy","gender":"Male"},
    {"id":15,"Name":"Florencia Knibley","gender":"Female"},
    {"id":16,"Name":"Brandyn Banyard","gender":"Male"},
    {"id":17,"Name":"Shellysheldon Wilcher","gender":"Male"},
    {"id":18,"Name":"Ruthie Gartside","gender":"Agender"},
    {"id":19,"Name":"Abeu Pallasch","gender":"Male"},
    {"id":20,"Name":"Ag Cullerne","gender":"Female"},
    {"id":21,"Name":"Phelia Hulme","gender":"Female"},
    {"id":22,"Name":"Sandie Lillicrap","gender":"Female"},
    {"id":23,"Name":"Noreen Heckner","gender":"Female"},
    {"id":24,"Name":"Lurlene de Grey","gender":"Female"},
    {"id":25,"Name":"Lorry Vasiltsov","gender":"Agender"},
    {"id":26,"Name":"Ivy Fonzo","gender":"Female"},
    {"id":27,"Name":"Randall Ouldcott","gender":"Male"},
    {"id":28,"Name":"Cahra Poynser","gender":"Polygender"},
    {"id":29,"Name":"Charisse Eliasen","gender":"Female"},
    {"id":30,"Name":"Ronnie Rosenfarb","gender":"Female"},
    {"id":31,"Name":"Vina Kays","gender":"Female"},
    {"id":32,"Name":"Yetta Dungey","gender":"Female"},
    {"id":33,"Name":"Orly Shakle","gender":"Female"},
    {"id":34,"Name":"Vanny O'Dennehy","gender":"Bigender"},
    {"id":35,"Name":"Skell Kennelly","gender":"Male"},
    {"id":36,"Name":"Barri Broggini","gender":"Agender"},
    {"id":37,"Name":"Elset Kayes","gender":"Female"},
    {"id":38,"Name":"Valli Rochell","gender":"Female"},
    {"id":39,"Name":"Camille Kale","gender":"Female"},
    {"id":40,"Name":"Nye Haffenden","gender":"Male"},
    {"id":41,"Name":"Flor Freeborn","gender":"Polygender"},
    {"id":42,"Name":"Ava Leverich","gender":"Female"},
    {"id":43,"Name":"Rosalia McWhinnie","gender":"Female"},
    {"id":44,"Name":"Orelle Aveyard","gender":"Female"},
    {"id":45,"Name":"Mildrid Iglesia","gender":"Female"},
    {"id":46,"Name":"Billy Thickett","gender":"Male"},
    {"id":47,"Name":"Rufe Davydzenko","gender":"Male"},
    {"id":48,"Name":"Marven Proske","gender":"Male"},
    {"id":49,"Name":"Tyrus Whitecross","gender":"Male"},
    {"id":50,"Name":"Kristyn Westoff","gender":"Female"},
    {"id":51,"Name":"Graham Giddings","gender":"Male"},
    {"id":52,"Name":"Glennie Lacaze","gender":"Female"},
    {"id":53,"Name":"Sibley Wenban","gender":"Female"},
    {"id":54,"Name":"Liz McConnell","gender":"Genderqueer"},
    {"id":55,"Name":"Janeczka Wards","gender":"Female"},
    {"id":56,"Name":"Zelig Cubbon","gender":"Male"},
    {"id":57,"Name":"Wiatt Offell","gender":"Male"},
    {"id":58,"Name":"Theresina Bristow","gender":"Female"},
    {"id":59,"Name":"Bonnee Giddons","gender":"Female"},
    {"id":60,"Name":"Paddie Tuttiett","gender":"Genderqueer"},
    {"id":61,"Name":"Zachary Simionescu","gender":"Bigender"},
    {"id":62,"Name":"Kathe MacKilroe","gender":"Female"},
    {"id":63,"Name":"Ines Beardall","gender":"Female"},
    {"id":64,"Name":"Rockey Wallett","gender":"Male"},
    {"id":65,"Name":"Guillermo Leteurtre","gender":"Male"},
    {"id":66,"Name":"Reggy Purcell","gender":"Male"},
    {"id":67,"Name":"Siffre Bower","gender":"Male"},
    {"id":68,"Name":"Wallis Rulf","gender":"Female"},
    {"id":69,"Name":"Mathian Marcham","gender":"Male"},
    {"id":70,"Name":"Burton Burrows","gender":"Male"},
    {"id":71,"Name":"Eldredge Walster","gender":"Male"},
    {"id":72,"Name":"Giulietta Iwanicki","gender":"Female"},
    {"id":73,"Name":"Charmion Ingre","gender":"Female"},
    {"id":74,"Name":"Felice Kislingbury","gender":"Male"},
    {"id":75,"Name":"Tallou Kindall","gender":"Female"},
    {"id":76,"Name":"Linnell Redit","gender":"Female"},
    {"id":77,"Name":"Felicdad Grzegorzewicz","gender":"Female"},
    {"id":78,"Name":"Sella Bartolozzi","gender":"Female"},
    {"id":79,"Name":"Marji Morton","gender":"Female"},
    {"id":80,"Name":"Madlin Cariss","gender":"Bigender"},
    {"id":81,"Name":"Viola Deans","gender":"Female"},
    {"id":82,"Name":"Regan MacCoveney","gender":"Male"},
    {"id":83,"Name":"Fanni Rawdall","gender":"Female"},
    {"id":84,"Name":"Kath Klimek","gender":"Female"},
    {"id":85,"Name":"Cristi Cudde","gender":"Female"},
    {"id":86,"Name":"Aime Tourner","gender":"Female"},
    {"id":87,"Name":"Muire Biagini","gender":"Female"},
    {"id":88,"Name":"Terri Baudasso","gender":"Female"},
    {"id":89,"Name":"Bryn Tregale","gender":"Male"},
    {"id":90,"Name":"Ermin Lennarde","gender":"Male"},
    {"id":91,"Name":"Marty Newbury","gender":"Male"},
    {"id":92,"Name":"Merrick Genty","gender":"Male"},
    {"id":93,"Name":"Karine Cubbini","gender":"Female"},
    {"id":94,"Name":"Haskell Kolin","gender":"Male"},
    {"id":95,"Name":"Rebe Greenshields","gender":"Female"},
    {"id":96,"Name":"Katya Chessil","gender":"Female"},
    {"id":97,"Name":"Jonie Serrell","gender":"Female"},
    {"id":98,"Name":"Dorrie Benardeau","gender":"Female"},
    {"id":99,"Name":"Kamila Schachter","gender":"Female"},
    {"id":100,"Name":"Cathleen Hounsom","gender":"Female"}]

let female_count = 0
let male_count = 0
let others_count = 0


for(emp of employees){
    if(emp.gender == "Female"){
        female_count++
    }
    else if(emp.gender == "Male"){
        male_count++
    } 
    else {
        others_count++
    }
}

console.log(" Females : ", female_count, "\n Males : ", male_count, "\n Others : ", others_count)
