let employees = [{"emp_id":1,"emp_name":"Rudyard Moff","email":"rmoff0@cnbc.com","gender":"Male"},
    {"emp_id":2,"emp_name":"Waylin McKellar","email":"wmckellar1@stumbleupon.com","gender":"Genderqueer"},
    {"emp_id":3,"emp_name":"Collen Guidi","email":"cguidi2@mysql.com","gender":"Female"},
    {"emp_id":4,"emp_name":"Alec Fearne","email":"afearne3@liveinternet.ru","gender":"Male"},
    {"emp_id":5,"emp_name":"Elden Leverich","email":"eleverich4@51.la","gender":"Male"},
    {"emp_id":6,"emp_name":"Barbaraanne Turbard","email":"bturbard5@yandex.ru","gender":"Female"},
    {"emp_id":7,"emp_name":"D'arcy Haccleton","email":"dhaccleton6@umich.edu","gender":"Male"},
    {"emp_id":8,"emp_name":"Harli Geeritz","email":"hgeeritz7@thetimes.co.uk","gender":"Female"},
    {"emp_id":9,"emp_name":"Chevalier Garrand","email":"cgarrand8@marketwatch.com","gender":"Male"},
    {"emp_id":10,"emp_name":"Boonie Goodoune","email":"bgoodoune9@cnet.com","gender":"Male"},
    {"emp_id":11,"emp_name":"Artemis Dunk","email":"adunka@dion.ne.jp","gender":"Male"},
    {"emp_id":12,"emp_name":"Minerva Tredgold","email":"mtredgoldb@mac.com","gender":"Female"},
    {"emp_id":13,"emp_name":"Oralle Sleath","email":"osleathc@blogspot.com","gender":"Female"},
    {"emp_id":14,"emp_name":"Christiana Kewish","email":"ckewishd@opensource.org","gender":"Female"},
    {"emp_id":15,"emp_name":"Bryn Engel","email":"bengele@nifty.com","gender":"Female"},
    {"emp_id":16,"emp_name":"Wilburt Giacopello","email":"wgiacopellof@nih.gov","gender":"Male"},
    {"emp_id":17,"emp_name":"Dane Blagburn","email":"dblagburng@blinklist.com","gender":"Male"},
    {"emp_id":18,"emp_name":"Hynda Bigg","email":"hbiggh@yellowpages.com","gender":"Bigender"},
    {"emp_id":19,"emp_name":"Ruthanne Dradey","email":"rdradeyi@123-reg.co.uk","gender":"Female"},
    {"emp_id":20,"emp_name":"Jessika Van der Kruijs","email":"jvanj@ed.gov","gender":"Female"},
    {"emp_id":21,"emp_name":"Tynan Mafham","email":"tmafhamk@bandcamp.com","gender":"Male"},
    {"emp_id":22,"emp_name":"Leshia Newman","email":"lnewmanl@independent.co.uk","gender":"Female"},
    {"emp_id":23,"emp_name":"Bert Crosier","email":"bcrosierm@cnet.com","gender":"Female"},
    {"emp_id":24,"emp_name":"Miguel Marczyk","email":"mmarczykn@comcast.net","gender":"Male"},
    {"emp_id":25,"emp_name":"Julie Dudenie","email":"jdudenieo@reddit.com","gender":"Male"},
    {"emp_id":26,"emp_name":"Brocky Paolino","email":"bpaolinop@hc360.com","gender":"Male"},
    {"emp_id":27,"emp_name":"Issiah Fairey","email":"ifaireyq@dagondesign.com","gender":"Male"},
    {"emp_id":28,"emp_name":"Raphael Leeming","email":"rleemingr@elpais.com","gender":"Male"},
    {"emp_id":29,"emp_name":"Alano Boc","email":"abocs@networkadvertising.org","gender":"Male"},
    {"emp_id":30,"emp_name":"Gerard Binge","email":"gbinget@shareasale.com","gender":"Male"},
    {"emp_id":31,"emp_name":"Tootsie Tempest","email":"ttempestu@spiegel.de","gender":"Female"},
    {"emp_id":32,"emp_name":"Janeva Oran","email":"joranv@zdnet.com","gender":"Female"},
    {"emp_id":33,"emp_name":"Shelba Ginglell","email":"sginglellw@comsenz.com","gender":"Female"},
    {"emp_id":34,"emp_name":"Felicio Egdal","email":"fegdalx@ft.com","gender":"Male"},
    {"emp_id":35,"emp_name":"Keir Lock","email":"klocky@berkeley.edu","gender":"Male"},
    {"emp_id":36,"emp_name":"Kalina Wein","email":"kweinz@google.ru","gender":"Female"},
    {"emp_id":37,"emp_name":"Ardisj Marconi","email":"amarconi10@shareasale.com","gender":"Female"},
    {"emp_id":38,"emp_name":"Vinson Bendare","email":"vbendare11@omniture.com","gender":"Male"},
    {"emp_id":39,"emp_name":"Dorthea Toomer","email":"dtoomer12@google.it","gender":"Female"},
    {"emp_id":40,"emp_name":"Arman Clues","email":"aclues13@squarespace.com","gender":"Male"},
    {"emp_id":41,"emp_name":"Willamina Bowkett","email":"wbowkett14@lulu.com","gender":"Female"},
    {"emp_id":42,"emp_name":"Stearne Harkness","email":"sharkness15@upenn.edu","gender":"Genderfluid"},
    {"emp_id":43,"emp_name":"Monika Borris","email":"mborris16@craigslist.org","gender":"Female"},
    {"emp_id":44,"emp_name":"Douglas Dillicate","email":"ddillicate17@about.com","gender":"Male"},
    {"emp_id":45,"emp_name":"Betta Gutans","email":"bgutans18@intel.com","gender":"Female"},
    {"emp_id":46,"emp_name":"Maje Hair","email":"mhair19@twitter.com","gender":"Non-binary"},
    {"emp_id":47,"emp_name":"Morlee Thomason","email":"mthomason1a@360.cn","gender":"Male"},
    {"emp_id":48,"emp_name":"Violet Vidineev","email":"vvidineev1b@ebay.co.uk","gender":"Female"},
    {"emp_id":49,"emp_name":"Kristofor Vasilic","email":"kvasilic1c@auda.org.au","gender":"Male"},
    {"emp_id":50,"emp_name":"Guenevere Gready","email":"ggready1d@amazonaws.com","gender":"Female"},
    {"emp_id":51,"emp_name":"Hanni Willshere","email":"hwillshere1e@cyberchimps.com","gender":"Female"},
    {"emp_id":52,"emp_name":"Malanie Wilshin","email":"mwilshin1f@techcrunch.com","gender":"Female"},
    {"emp_id":53,"emp_name":"Cybill MacEntee","email":"cmacentee1g@photobucket.com","gender":"Female"},
    {"emp_id":54,"emp_name":"Leticia Southern","email":"lsouthern1h@tuttocitta.it","gender":"Female"},
    {"emp_id":55,"emp_name":"Leese Cultcheth","email":"lcultcheth1i@reuters.com","gender":"Female"},
    {"emp_id":56,"emp_name":"Sibeal Coughtrey","email":"scoughtrey1j@wikimedia.org","gender":"Female"},
    {"emp_id":57,"emp_name":"Dedra Le Fevre","email":"dle1k@hostgator.com","gender":"Female"},
    {"emp_id":58,"emp_name":"Dedra Werny","email":"dwerny1l@comcast.net","gender":"Female"},
    {"emp_id":59,"emp_name":"Barrett Branni","email":"bbranni1m@cafepress.com","gender":"Male"},
    {"emp_id":60,"emp_name":"Merl Ridding","email":"mridding1n@unicef.org","gender":"Female"},
    {"emp_id":61,"emp_name":"Trent Grimsdell","email":"tgrimsdell1o@nbcnews.com","gender":"Male"},
    {"emp_id":62,"emp_name":"Imojean Guarin","email":"iguarin1p@senate.gov","gender":"Female"},
    {"emp_id":63,"emp_name":"Anders Clows","email":"aclows1q@huffingtonpost.com","gender":"Male"},
    {"emp_id":64,"emp_name":"Em Curtain","email":"ecurtain1r@delicious.com","gender":"Female"},
    {"emp_id":65,"emp_name":"Roth Lodovichi","email":"rlodovichi1s@bigcartel.com","gender":"Male"},
    {"emp_id":66,"emp_name":"Josiah Fitzsimon","email":"jfitzsimon1t@si.edu","gender":"Male"},
    {"emp_id":67,"emp_name":"Talbot Simony","email":"tsimony1u@marketwatch.com","gender":"Genderfluid"},
    {"emp_id":68,"emp_name":"Jayson Symons","email":"jsymons1v@elegantthemes.com","gender":"Male"},
    {"emp_id":69,"emp_name":"Claudelle Lorraway","email":"clorraway1w@slideshare.net","gender":"Non-binary"},
    {"emp_id":70,"emp_name":"Lea Dyers","email":"ldyers1x@wikia.com","gender":"Female"},
    {"emp_id":71,"emp_name":"Ebba Morales","email":"emorales1y@europa.eu","gender":"Female"},
    {"emp_id":72,"emp_name":"Joachim Weekes","email":"jweekes1z@ezinearticles.com","gender":"Male"},
    {"emp_id":73,"emp_name":"Rosemaria Sanderson","email":"rsanderson20@newyorker.com","gender":"Female"},
    {"emp_id":74,"emp_name":"Melba De Dei","email":"mde21@fda.gov","gender":"Bigender"},
    {"emp_id":75,"emp_name":"Shina McCrone","email":"smccrone22@mozilla.com","gender":"Female"},
    {"emp_id":76,"emp_name":"Edward Ducker","email":"educker23@bloglines.com","gender":"Male"},
    {"emp_id":77,"emp_name":"Rosemonde Pury","email":"rpury24@ted.com","gender":"Female"},
    {"emp_id":78,"emp_name":"Neila Robjohns","email":"nrobjohns25@netscape.com","gender":"Female"},
    {"emp_id":79,"emp_name":"Aile McGray","email":"amcgray26@google.it","gender":"Female"},
    {"emp_id":80,"emp_name":"Guendolen Cammack","email":"gcammack27@instagram.com","gender":"Female"},
    {"emp_id":81,"emp_name":"Gaultiero Malbon","email":"gmalbon28@mozilla.com","gender":"Male"},
    {"emp_id":82,"emp_name":"Georgianne Scipsey","email":"gscipsey29@fda.gov","gender":"Female"},
    {"emp_id":83,"emp_name":"Britt Hebbs","email":"bhebbs2a@hhs.gov","gender":"Male"},
    {"emp_id":84,"emp_name":"Milt Impey","email":"mimpey2b@wordpress.com","gender":"Male"},
    {"emp_id":85,"emp_name":"Lind Perigeaux","email":"lperigeaux2c@fastcompany.com","gender":"Male"},
    {"emp_id":86,"emp_name":"Lisha Hammelberg","email":"lhammelberg2d@gizmodo.com","gender":"Female"},
    {"emp_id":87,"emp_name":"Karlyn Fidilis","email":"kfidilis2e@cloudflare.com","gender":"Female"},
    {"emp_id":88,"emp_name":"Chlo Liddy","email":"cliddy2f@nsw.gov.au","gender":"Female"},
    {"emp_id":89,"emp_name":"Vitoria Woehler","email":"vwoehler2g@flickr.com","gender":"Female"},
    {"emp_id":90,"emp_name":"Raimund Hearthfield","email":"rhearthfield2h@prnewswire.com","gender":"Male"},
    {"emp_id":91,"emp_name":"Riley Dmitrievski","email":"rdmitrievski2i@nasa.gov","gender":"Male"},
    {"emp_id":92,"emp_name":"Patrizius Salla","email":"psalla2j@opensource.org","gender":"Male"},
    {"emp_id":93,"emp_name":"Konstantine Blasli","email":"kblasli2k@last.fm","gender":"Male"},
    {"emp_id":94,"emp_name":"Rubin Brydie","email":"rbrydie2l@163.com","gender":"Male"},
    {"emp_id":95,"emp_name":"Dacy Bocking","email":"dbocking2m@tiny.cc","gender":"Female"},
    {"emp_id":96,"emp_name":"Gianni Stenett","email":"gstenett2n@bravesites.com","gender":"Male"},
    {"emp_id":97,"emp_name":"Cherice Josh","email":"cjosh2o@php.net","gender":"Female"},
    {"emp_id":98,"emp_name":"Shell Sabatier","email":"ssabatier2p@zdnet.com","gender":"Female"},
    {"emp_id":99,"emp_name":"Hal Goggan","email":"hgoggan2q@gnu.org","gender":"Male"},
    {"emp_id":100,"emp_name":"Tobin Simes","email":"tsimes2r@baidu.com","gender":"Male"}
]

function displayEmployees() {
    rows = ``

    for(employee of employees){
        if(employee.gender == "Male"){
            rows+= ` <tr>
                    <td>${employee.emp_id}</td>
                    <td>${employee.emp_name}</td>
                    <td>${employee.email}</td>
                </tr> `;

            console.log(employee.emp_id)
        }
    }

    document.getElementById("empdetails").innerHTML = rows;
}
